"""Display taxonomy and editorial priorities. Sizes do not encode measured popularity."""
SECTIONS = [
    ("systems", "Systems & software engines", "#c55226", "linux microkernel exokernel security jupyter wolfram cgal cad simulation"),
    ("gpu", "GPU & numerical code", "#2964b2", "cuda opencl metal hip shader triton pallas compute-cpu dispatch tf fusion"),
    ("ml", "Machine learning", "#7552bd", "psd rkhs gp rbf kernel-families graph-ml string fisher ntk nngp mmd stein-ml quantum attention"),
    ("filters", "Filters & transforms", "#087e63", "cnn filter convolution morphology transform dirichlet fejer reconstruction"),
    ("algebra", "Algebra & nullspaces", "#bf3d65", "nullspace group ring module operator congruence category kernel-pair isogeny code semigroup radical"),
    ("statistics", "Probability & statistics", "#3b7e91", "kde regression probability markov likelihood stein-prob determinantal"),
    ("analysis", "Mathematical analysis", "#5c6bca", "integral green heat poisson mollifier singular hilbert cauchy bergman szego"),
    ("geometry", "Geometry & sets", "#966136", "polygon viability discriminating perfect saturation kern"),
    ("graphs", "Graphs & game theory", "#68831e", "digraph game"),
    ("proofs", "Proofs & formal logic", "#9b760b", "lean lcf belief"),
    ("algorithms", "Algorithms & optimization", "#536b7b", "kernelization lossy kernel-search path-kernel"),
    ("physics", "Physics & engineering", "#aa553d", "atomic flame fuel volterra memory collision sensitivity averaging shield xc bethe kpm sph"),
    ("biology", "Biology & food", "#5d8736", "grain nut dispersal"),
    ("space", "Spacecraft data", "#8a5da2", "spice"),
]

PRIORITY = "linux cuda cnn psd nullspace lean jupyter convolution filter rbf gp triton pallas ntk rkhs integral kde heat markov compute-cpu microkernel metal attention cgal cad spice quantum opencl hip fusion dispatch tf kernelization group ring probability morphology".split()
MAJOR = "linux cuda cnn psd nullspace lean".split()
# Authored coordinates keep the common-kernel map stable while the reader explores.
OVERVIEW = {
    "linux": [160, 155], "cuda": [555, 155], "lean": [1035, 155],
    "microkernel": [310, 65], "jupyter": [70, 365],
    "triton": [470, 335], "pallas": [670, 310], "lcf": [1080, 355],
    "nullspace": [155, 625], "integral": [330, 475],
    "cnn": [865, 455], "filter": [690, 535], "convolution": [975, 660],
    "psd": [500, 750], "rkhs": [305, 830], "rbf": [720, 810],
    "gp": [915, 890], "kde": [1130, 530], "heat": [1140, 720],
    "markov": [1120, 900],
}

ALIASES = {
    "linux": "Linux / OS", "cuda": "CUDA", "cnn": "CNN filter", "psd": "SVM kernel",
    "nullspace": "Nullspace", "lean": "Lean", "jupyter": "Jupyter", "microkernel": "Microkernel",
    "convolution": "Convolution", "filter": "Image filter", "rbf": "Gaussian / RBF",
    "gp": "Gaussian process", "triton": "Triton", "pallas": "JAX Pallas", "rkhs": "Reproducing kernel",
    "integral": "Integral kernel", "kde": "Density estimation", "heat": "Heat kernel", "markov": "Markov kernel",
    "lcf": "LCF / HOL", "compute-cpu": "BLAS microkernel", "kernel-families": "Other ML kernels",
    "graph-ml": "Graph similarity", "digraph": "Digraph kernel", "stein-ml": "Stein discrepancy",
    "stein-prob": "Stein identity", "kernelization": "Kernelization", "lossy": "Lossy kernelization",
    "category": "Categorical kernel", "module": "Module / Lie algebra", "group": "Group homomorphism",
    "ring": "Ring homomorphism", "operator": "Differential nullspace", "code": "Parity-check code",
    "congruence": "Congruence kernel", "kernel-pair": "Kernel pair", "isogeny": "Isogeny kernel",
    "attention": "Linear attention", "ntk": "Neural tangent kernel", "nngp": "Neural-network GP",
    "mmd": "Kernel mean embedding", "quantum": "Quantum kernel", "fisher": "Fisher kernel",
    "string": "String kernel", "determinantal": "Determinantal kernel", "morphology": "Morphology",
    "reconstruction": "Reconstruction", "transform": "Fourier / Laplace", "dirichlet": "Dirichlet kernel",
    "fejer": "Fejér kernel", "mollifier": "Mollifier", "singular": "Singular kernel",
    "hilbert": "Hilbert transform", "cauchy": "Cauchy kernel", "poisson": "Poisson kernel",
    "green": "Green function", "bergman": "Bergman kernel", "szego": "Szegő kernel",
    "probability": "Probability kernel", "regression": "Kernel regression", "likelihood": "Density kernel",
    "volterra": "Volterra series", "memory": "Memory kernel", "dispersal": "Seed dispersal",
    "collision": "Collision kernel", "sensitivity": "Sensitivity kernel", "averaging": "Averaging kernel",
    "shield": "Radiation point kernel", "xc": "Exchange–correlation", "bethe": "Bethe–Salpeter",
    "kpm": "Kernel polynomial method", "sph": "SPH smoothing", "path-kernel": "Generating function",
    "polygon": "Visibility kernel", "viability": "Viability kernel", "discriminating": "Discriminating kernel",
    "perfect": "Perfect kernel", "saturation": "Topological set kernel", "semigroup": "Semigroup kernel",
    "radical": "Squarefree kernel", "belief": "Belief revision", "game": "Cooperative game",
    "kernel-search": "Kernel Search", "kern": "Section kern", "metal": "Metal", "opencl": "OpenCL",
    "hip": "AMD HIP", "shader": "Compute shader", "dispatch": "Operator dispatch", "tf": "TensorFlow OpKernel",
    "fusion": "Fused kernel", "exokernel": "Exokernel", "security": "Security kernel", "wolfram": "Wolfram kernel",
    "cgal": "CGAL geometry", "cad": "CAD modeling", "simulation": "Simulation engine", "spice": "NASA SPICE",
    "grain": "Corn / grain", "nut": "Nut kernel", "atomic": "Atomic core", "flame": "Ignition kernel", "fuel": "TRISO fuel",
}

TYPES = {
    "linux": "OS component", "cuda": "GPU routine", "cnn": "Weight tensor", "psd": "Pairwise function",
    "nullspace": "Vector subspace", "lean": "Proof checker", "jupyter": "Language process",
    "lcf": "Inference engine", "wolfram": "Evaluation engine", "microkernel": "OS architecture", "exokernel": "OS architecture",
    "security": "Trusted mechanisms", "cgal": "Geometry library", "cad": "Geometry engine", "simulation": "Event scheduler",
    "filter": "Array of weights", "morphology": "Structuring element", "spice": "Data file", "kernelization": "Reduced problem",
    "lossy": "Approximate reduction", "kernel-search": "Candidate variables", "belief": "Minimal premise set",
    "game": "Payoff set", "radical": "Integer", "path-kernel": "Generating-function factor",
    "grain": "Whole grain", "nut": "Inner seed", "atomic": "Atomic core", "flame": "Ignition region", "fuel": "Fuel particle",
    "group": "Normal subgroup", "ring": "Ideal", "module": "Submodule / Lie ideal", "operator": "Function space",
    "congruence": "Equivalence relation", "category": "Universal morphism", "kernel-pair": "Pullback object",
    "isogeny": "Finite subgroup scheme", "code": "Linear code", "semigroup": "Minimal ideal",
    "integral": "Two-input function", "convolution": "Convolution weights", "heat": "Fundamental solution",
    "probability": "Measure-valued mapping", "markov": "Transition probabilities", "likelihood": "Unnormalized density",
    "kde": "Smoothing function", "gp": "Covariance function", "rkhs": "Reproducing function",
    "polygon": "Visibility region", "viability": "Controllable safe set", "discriminating": "Robust safe set",
}
DEFAULT_TYPES = {"zero":"Zero fiber / relation", "influence":"Weighting function", "similarity":"Pairwise function", "subset":"Set / region", "compute":"Executable routine", "engine":"Software component", "reduction":"Problem reduction", "space":"Data file", "physical":"Physical object"}

# Only these explicit relationships receive named edges. Other catalogue cross-
# references are navigation suggestions, not assertions of equivalence or ancestry.
LINKS = [
 ("linux","microkernel","alternative architecture","specialization"),
 ("linux","cuda","GPU driver services","uses"),
 ("linux","jupyter","runs as a process","uses"),
 ("lean","lcf","proof-checking approaches","related"),
 ("cuda","cnn","executes the operation","uses"),
 ("cuda","triton","another GPU language","related"),
 ("cuda","pallas","JAX GPU programming","related"),
 ("cnn","filter","learned filter weights","specialization"),
 ("filter","convolution","discrete convolution","related"),
 ("cnn","dispatch","framework implementation","uses"),
 ("convolution","integral","shift-invariant case","specialization"),
 ("integral","nullspace","representation vs zero inputs","contrast"),
 ("psd","rbf","a PSD kernel choice","specialization"),
 ("psd","rkhs","feature inner products","related"),
 ("rbf","gp","a covariance choice","uses"),
 ("rbf","kde","same shape, different role","contrast"),
 ("heat","convolution","evolves initial data","uses"),
 ("heat","markov","Brownian transition density","related"),
 ("heat","green","heat-equation fundamental solution","specialization"),
 ("gp","psd","PSD covariance requirement","related"),
 ("ntk","psd","gradient inner products","specialization"),
 ("nngp","gp","infinite-width covariance","specialization"),
 ("graph-ml","psd","compares graphs","specialization"),
 ("graph-ml","digraph","a function vs a vertex set","contrast"),
 ("stein-prob","stein-ml","two different Stein objects","contrast"),
 ("compute-cpu","microkernel","two meanings of microkernel","contrast"),
 ("probability","markov","transition special case","specialization"),
 ("probability","likelihood","measure vs density expression","contrast"),
 ("kde","regression","different weighted estimates","related"),
 ("nullspace","group","zero vs identity fiber","related"),
 ("nullspace","module","linear generalization","specialization"),
 ("module","category","abstract universal property","related"),
 ("group","ring","homomorphism kernels","related"),
 ("group","congruence","induced equivalence relation","related"),
 ("congruence","kernel-pair","categorical construction","related"),
 ("nullspace","code","Hc = 0","uses"),
 ("filter","reconstruction","resampling weights","uses"),
 ("filter","morphology","weights vs a neighborhood","contrast"),
 ("transform","convolution","convolution theorem","related"),
 ("kernelization","lossy","approximate variant","specialization"),
 ("cgal","cad","different geometry engines","contrast"),
 ("triton","fusion","fuses operations","uses"),
 ("pallas","dispatch","custom JAX implementation","uses"),
 ("integral","bergman","also a reproducing kernel","related"),
 ("rkhs","bergman","holomorphic function space","specialization"),
 ("integral","green","represents a solution operator","related"),
 ("sph","convolution","local weighted smoothing","related"),
]
